### PR TITLE
V1.0

### PR DESCRIPTION
**Pull request by kenao123**
finished assignment 2, JPA and controllers done

### CODE REVIEW

**Comment by kenao123** [comment]
approved, good code, tested

**Comment by mikedivine** [comment]
Looks good. Let's goooo baaabyy!!

**Comment by rfrost30** [comment]
looks good, ready to implement the front end

**Comment by ladiitati** [comment]
Approved! Looks Good

**Comment by JADuarte18** [comment]
All the entities have the required setters, getters, and relations needed. The controllers return the correct data and error-checking is used accordingly. LGTM! Approved.

**Comment by anthonymatricia** [comment]
All of the JPA Entities are complete and look good. The controllers were developed nicely, and any previous issues were resolved. Relationships look great as well. Well done! Approved.

**Review by JADuarte18 — APPROVED** [review]

**Pull request closed without merging**
